// <auto-generated />
namespace DBReading.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReadingGroupOptionData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReadingGroupOptionData));
        
        string IMigrationMetadata.Id
        {
            get { return "201701280524156_ReadingGroupOptionData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
